apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-eta-app-deploy
  labels:
    app: banking-eta-app-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: banking-eta-app
  template:
    metadata:
      labels:
        app: banking-eta-app
    spec:
      containers:
      - name: banking-eta-container
        image: bsvk38/bankapp-eta-app:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: banking-eta-service
  labels:
    app: banking-eta-app
spec:
  selector:
    app: banking-eta-app

  type: NodePort
  ports:
  - nodePort: 31033
    port: 8081
    targetPort: 8081
